name: login_project
description: Login App.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  fluttertoast: ^8.1.1
  flutter_svg: ^1.1.6
  json_serializable: ^6.5.4
  provider: ^6.0.4
  sqflite: ^2.2.0+3
  json_annotation: ^4.7.0
  get_it: ^7.2.0
  path_provider: ^2.0.11
  dio: ^4.0.6
  cached_network_image: ^3.2.2
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/translations/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf